version: "3"

services:
  builder:
    build:
      context: builder
    image: iwillio/builder

  nodiwilld:
    build:
      context: .
    image: iwillio/iwill
    command: /opt/iwillio/bin/nodiwilld.sh --data-dir /opt/iwillio/bin/data-dir -e --http-alias=nodiwilld:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888
    hostname: nodiwilld
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodiwill-data-volume:/opt/iwillio/bin/data-dir
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

  kiwilld:
    image: iwillio/iwill
    command: /opt/iwillio/bin/kiwilld --wallet-dir /opt/iwillio/bin/data-dir --http-server-address=127.0.0.1:8900 --http-alias=kiwilld:8900 --http-alias=localhost:8900
    hostname: kiwilld
    links:
      - nodiwilld
    volumes:
      - kiwilld-data-volume:/opt/iwillio/bin/data-dir
    stop_grace_period: 10m

volumes:
  nodiwill-data-volume:
    external: true
  kiwilld-data-volume:
    external: true
